<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="red"> <color rgba="0.6 0 0 1"/> </material>
    <material name="green"> <color rgba="0 0.6 0 1"/> </material>
    <material name="blue"> <color rgba="0 0 0.9 1"/> </material>
    <material name="gray"> <color rgba="0.6 0.6 0.6 1"/> </material>
    <material name="light_gray"> <color rgba="0.8 0.8 0.8 1"/> </material>
    <material name="dark_gray"> <color rgba="0.4 0.4 0.4 1"/> </material>
    <material name="black"> <color rgba="0 0 0 1"/> </material>
    <material name="white"> <color rgba="1 1 1 1"/> </material>

    <xacro:macro name="box_inertia" params="m x y z xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                      iyy="${m*(x*x+z*z)/12}" iyz="0"
                      izz="${m*(x*x+y*y)/12}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="rect_tube_inertia" params="m t x y z xyz rpy">
        <!-- profilin uzun kısmı için x ekseni kullanılıyor -->
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${m/12*((y*z**3)-((y-2*t)*(z-2*t)**3))}"
                     iyy="${m/12*((x*z**3)-((x-2*t)*(z-2*t)**3))}"
                     izz="${m/12*((x*y**3)-((x-2*t)*(y-2*t)**3))}"
                     ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="u_rect_tube_inertia" params="m t x y z xyz rpy">
        <!-- profilin uzun kısmı için x ekseni kullanılıyor -->
        <!-- boş olan taraf üste (+z) bakıyor -->
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <!-- <inertia ixx="${m/12*(2*(y*t**3)+(y*(z-2*t)**3))}"
                     iyy="${m/12*(2*(z*t**3)+(x*(z-2*t)**3))}"
                     izz="${m/12*((x*y**3)-((x-2*t)*(y-2*t)**3))}"
                     ixy="0" ixz="0" iyz="0"/> -->
            <inertia ixx="${m*((y*y+z*z)/12-((y-t)*(y-t)*z*z)/(12*(1-(t*y*z)/(x*y*z))))}" 
                iyy="${m*((x*x+z*z)/12-(x*x*(z-t)*(z-t))/(12*(1-(t*x*z)/(x*y*z))))}" 
                izz="${m*((x*x+y*y)/12-(x*x*(y-t)*(y-t))/(12*(1-(t*x*y)/(x*y*z))))}"
                ixy="0" iyz="0" ixz="0"/>

        </inertial>
    </xacro:macro>

    <xacro:macro name="structure_inertia" params="step xyz rpy">
        <!-- structureın uzun kısmı için x ekseni kullanılıyor -->
        <!-- boş olan taraf üste (+z) bakıyor -->
        <xacro:u_rect_tube_inertia m="${step*0.016}" t="0.002" x="${step*0.025}" 
                                   y="0.05" z="0.05" xyz="${xyz}" rpy="${rpy}"/>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r l xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+l*l)/12}" ixy="0" ixz="0"
                      iyy="${m*(3*r*r+l*l)/12}" iyz="0"
                      izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>


    <xacro:macro name="structure" params="link_name step xyz rpy">
        <link name="${link_name}">
            <collision>
                <geometry>
                    <box size="${step*0.05/2} 0.05 0.05"/>
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </collision>

            <visual>
                <material name="white"/>
                <geometry>
                    <box size="${step*0.05/2} 0.05 0.05"/>
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </visual>
            
            <xacro:structure_inertia step="${step}" xyz="${xyz}" rpy="${rpy}"/>
            <gazebo>
                <material>Gazebo/White</material>
            </gazebo>
        </link>
    </xacro:macro>

    <xacro:macro name="traction_wheel" params="link_name xyz rpy">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.0375"/>
                </geometry>
                <material name="gray"/>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.0375"/>
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" l="0.0375" xyz="${xyz}" rpy="${rpy}"/>
            <gazebo>
                <material>Gazebo/Gray</material>
                <mu>0.2</mu>
                <mu2>1.</mu2>
                <surface>
                    <friction>
                        <ode>
                        <mu>0.2</mu>
                        <mu2>1.</mu2>
                        </ode>
                    </friction>
                </surface>
            </gazebo>
        </link>
    </xacro:macro>

    <xacro:macro name="frictionless_wheel" params="link_name xyz rpy">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.0375"/>
                </geometry>
                <material name="blue"/>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="0.0375"/>
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" l="0.0375" xyz="${xyz}" rpy="${rpy}"/>
            <gazebo>
                <material>Gazebo/Blue</material>
                <mu>0.</mu>
                <mu2>0.</mu2>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.</mu>
                            <mu2>0.</mu2>
                        </ode>
                    </friction>
                </surface>
            </gazebo>
        </link>
    </xacro:macro>
</robot>