<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="odom"/>
  <joint name="odom_link" type="fixed">
    <parent link="odom" />
    <child link="base_footprint" />
    <origin xyz="0.14 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint" />

  <xacro:property name="base_z" value="0.58" />
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.72 0.54  ${base_z}" />
      </geometry>
      <material name="white" />
      <origin xyz="0 0 ${base_z/2}" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <box size="0.72 0.54  ${base_z}" />
      </geometry>
      <origin xyz="0 0 ${base_z/2}" rpy="0 0 0" />
    </collision>
    <xacro:box_inertia m="16." x="0.72" y="0.54" z="${base_z}" xyz="0 0 ${base_z/2}" rpy="0 0 0" />
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="-0.14 0 0.125" rpy="0 0 0" />
  </joint>

  <link name="bno055" />
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />  <!-- Attach to the appropriate link -->
    <child link="bno055" />
    <origin xyz="-0.36 0 0.335" rpy="0 0 0" />  <!-- Adjust position -->
  </joint>

  <link name="base_front">
    <visual>
      <geometry>
        <cylinder radius="0.316" length="${base_z}" />
      </geometry>
      <material name="white" />
      <origin xyz="0 0 ${base_z/2}" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.316" length="${base_z}" />
      </geometry>
      <origin xyz="0 0 ${base_z/2}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="10." r="0.316" l="${base_z}" xyz="0 0 ${base_z/2}" rpy="0 0 0" />
  </link>
  <joint name="base_front_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_front" />
    <origin xyz="0.36 0 0" rpy="0 0 0" />
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.125" length="0.05" />
      </geometry>
      <material name="black" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.125" length="0.05" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="0.5" r="0.125" l="0.05" xyz="0 0 0" rpy="0 0 0" />
  </link>
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel" />
    <origin xyz="0 0.25 0" rpy="1.57 0 3.14" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.125" length="0.05" />
      </geometry>
      <material name="black" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.125" length="0.05" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="0.5" r="0.125" l="0.05" xyz="0 0 0" rpy="0 0 0" />
  </link>
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel" />
    <origin xyz="0 -0.25 0" rpy="1.57 0 3.14" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="brush">
    <visual>
      <geometry>
        <cylinder radius="0.32" length="0.12" />
      </geometry>
      <material name="blue" />
      <origin xyz="0 0 0.06" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.32" length="0.12" />
      </geometry>
      <origin xyz="0 0 0.06" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="3" r="0.32" l="0.12" xyz="0 0 0.06" rpy="0 0 0" />
  </link>
  <joint name="brush_joint" type="fixed">
    <parent link="base_front" />
    <child link="brush" />
    <origin xyz="0.095 0 -0.125" rpy="0 0 0" />
    <!-- <axis xyz="0 0 1"/> -->
  </joint>

  <xacro:property name="scan_l" value="0.04" />
  <xacro:property name="scan_r" value="0.06" />
  <link name="base_scan">
    <visual>
      <geometry>
        <cylinder radius="${scan_r}" length="${scan_l}" />
      </geometry>
      <material name="black" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${scan_r}" length="${scan_l}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="0.4" r="${scan_r}" l="${scan_l}" xyz="0 0 0" rpy="0 0 0" />
  </link>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_scan" />
    <origin xyz="0.680 0 0.58" rpy="0 0 -1.84847821" />
    <!-- <axis xyz="0 0 1"/> -->
  </joint>

</robot>