<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="base_footprint" />

  <xacro:property name="wheel_diameter" value="0.1"/>
  <xacro:property name="wheel_length" value="0.044"/>
  <xacro:property name="structure_width" value="0.05"/>
  <xacro:property name="structure_step_width" value="0.025"/>

  <xacro:nfr_structure link_name="base_structure" step="12" xyz="0 0 0" rpy="3.14 0 1.57"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_structure"/>
    <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
  </joint>

  <xacro:nfr_structure link_name="left_structure" step="16" xyz="0 0 0" rpy="3.14 0 0"/>
  <joint name="left_structure_joint" type="fixed">
    <parent link="base_structure"/>
    <child link="left_structure"/>
    <origin xyz="0 ${structure_step_width*6+structure_width/2} 0" rpy="0 0 0"/>
  </joint>
  
  <xacro:nfr_structure link_name="right_structure" step="16" xyz="0 0 0" rpy="3.14 0 0"/>
  <joint name="right_structure_joint" type="fixed">
    <parent link="base_structure"/>
    <child link="right_structure"/>
    <origin xyz="0 -${structure_step_width*6+structure_width/2} 0" rpy="0 0 0"/>
  </joint>


  <xacro:traction_wheel link_name="front_left_wheel" xyz="0 0 0" rpy="0 0 0"/>
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="left_structure"/>
    <child link="front_left_wheel"/>
    <origin xyz="${structure_step_width*6} ${structure_width/2+wheel_length/2} 0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <xacro:traction_wheel link_name="front_right_wheel" xyz="0 0 0" rpy="0 0 0"/>
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="right_structure"/>
    <child link="front_right_wheel"/>
    <origin xyz="${structure_step_width*6} -${structure_width/2+wheel_length/2} 0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <xacro:nfr_omni_wheel link_name="rear_left_wheel" xyz="0 0 0" rpy="0 0 0"/>
  <joint name="rear_left_wheel_joint" type="fixed">
    <parent link="left_structure"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-${structure_step_width*6} ${structure_width/2+wheel_length/2} 0" rpy="-1.57 0 0"/>
  </joint>

  <!-- <xacro:frictionless_wheel link_name="rear_right_wheel" xyz="0 0 0" rpy="0 0 0"/>
  <joint name="rear_right_wheel_joint" type="fixed">
    <parent link="right_structure"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-${structure_step_width*6} -${structure_width/2+wheel_length/2} 0" rpy="-1.57 0 0"/>
  </joint> -->

  <xacro:nfr_omni_wheel link_name="rear_right_wheel" xyz="0 0 0" rpy="0 0 0"/>
  <joint name="rear_right_wheel_joint" type="fixed">
    <parent link="right_structure"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-${structure_step_width*6} -${structure_width/2+wheel_length/2} 0" rpy="-1.57 0 0"/>
  </joint>


</robot>