<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="nfr_wheel_diam" value="0.1"/>

    <xacro:macro name="frictionless_wheel" params="link_name xyz rpy">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <cylinder radius="${nfr_wheel_diam/2}" length="0.0375"/>
                </geometry>
                <material name="nfr_blue"/>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${nfr_wheel_diam/2}" length="0.0375"/>
                </geometry>
                <origin xyz="${xyz}" rpy="${rpy}"/>
            </collision>
            <xacro:nfr_cylinder_inertia m="0.1" r="${nfr_wheel_diam/2}" l="0.0375" xyz="${xyz}" rpy="${rpy}"/>
            <gazebo>
                <material>Gazebo/Blue</material>
                <mu>0.</mu>
                <mu2>0.</mu2>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.</mu>
                            <mu2>0.</mu2>
                        </ode>
                    </friction>
                </surface>
            </gazebo>
        </link>
    </xacro:macro>

</robot>